Repository Nouvelle-Techno-fr/JeBenevole.fr, pull requests merged in 2021-10, with the labels that each got.

#62 Crud categories
  src/Controller/Admin/CategoryController.php
  src/Entity/Categories.php
  src/Form/CategoryType.php
  src/Repository/CategoriesRepository.php
  templates/admin/category/_form.html.twig
  templates/admin/category/create-and-edit.html.twig
  templates/admin/category/list.html.twig
  templates/admin/category/show.html.twig
  translations/messages.fr.yaml
Labels: enhancement

#65 Association refacto
  public/.htaccess
  src/Controller/AssociationController.php
  src/Entity/Associations.php
  src/Form/AssociationType.php
  src/Validator/isFromYoutube.php
  src/Validator/isFromYoutubeValidator.php
  translations/messages.fr.yaml
  translations/validators.fr.yaml
Labels: refacto

#63 Register and login
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  public/assets/logo.png
  src/Controller/OfferController.php
  src/Controller/ProfileController.php
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  src/Entity/Users.php
  src/Form/OfferType.php
  src/Form/ProfileFormType.php
  src/Form/RegistrationFormType.php
  src/Security/EmailVerifier.php
  src/Security/LoginAuthenticator.php
  src/Security/UserChecker.php
  src/Security/UserVoter.php
  symfony.lock
  templates/base.html.twig
  templates/profile/edit.html.twig
  templates/profile/show.html.twig
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
  templates/security/login.html.twig
  translations/messages.fr.yaml
  translations/validators.fr.yaml
Labels: enhancement, small fix

#64 Axentix setup
  public/assets/css/axentix.min.css
  public/assets/js/axentix.min.js
  templates/base.html.twig
Labels: enhancement

#66 Small fixes and clean
  src/Controller/.gitignore
  src/Controller/AssociationController.php
  src/Controller/DefaultController.php
  src/Controller/OfferController.php
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  src/Entity/.gitignore
  src/Form/OfferType.php
  src/Repository/.gitignore
  src/Repository/AssociationsRepository.php
  src/Security/AssociationVoter.php
  src/Security/LoginAuthenticator.php
  src/Security/OfferVoter.php
  templates/default/homepage.html.twig
  templates/default/rgpd.html.twig
  templates/offer/_form.html.twig
  templates/offer/list.html.twig
  templates/registration/register.html.twig
  translations/.gitignore
  translations/messages.fr.yaml
Labels: enhancement, refacto
