Repository Nouvelle-Techno-fr/JeBenevole.fr, pull requests merged in 2022-04, with the labels that each got.

#102 Messages Flash
  src/Controller/AssociationController.php
  src/Controller/DefaultController.php
  src/Controller/OfferController.php
  src/Controller/ProfileController.php
  src/Controller/RegistrationController.php
  templates/base.html.twig
  templates/layout_front_office.html.twig
  templates/registration/register.html.twig
  translations/messages.fr.yaml
Labels: enhancement

#104 Minor changes
  .env
  public/assets/js/admin.js
  public/assets/js/validations/association.js
  public/assets/js/validations/login.js
  public/assets/js/validations/offer.js
  public/assets/js/validations/profile.js
  public/assets/js/validations/registration.js
Labels: small fix

#105 Contact form validation js
  public/assets/js/validations/contact.js
  templates/default/contact.html.twig
Labels: enhancement

#107 Anonymize finalize
  src/Form/OfferType.php
  src/Service/AnonymizeService.php
Labels: enhancement, MVP
